name: Injection
on: pull_request
jobs:
  inject:
    runs-on: ubuntu-latest
    env: 
      PR_TITLE: ${{ github.event.pull_request.title }}
    steps:
      - run: echo "${PR_TITLE}"
      - run: echo "${{ github.event.pull_request.title }}"