name: Conditions
on: push
jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    env:
      RUN_ID: ${{ github.run_id }}
    steps:
      - run: echo "${RUN_ID}"
      # ワークフロー実行IDに「1」が含まれていれば実行される
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '1') }} 